#ifndef QNOTIFICATIONS_GLOBAL_H
#define QNOTIFICATIONS_GLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
# if defined(QT_BUILD_NOTIFICATIONS_LIB)
#   define Q_NOTIFICATIONS_EXPORT Q_DECL_EXPORT
# else
#   define Q_NOTIFICATIONS_EXPORT Q_DECL_IMPORT
# endif
#else
# define Q_NOTIFICATIONS_EXPORT
#endif

QT_END_NAMESPACE

#endif // QNOTIFICATIONS_GLOBAL_H
